# Generated by Django 3.0.5 on 2020-04-30 05:34

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('handle', models.SlugField(blank=True, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='collections/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('handle', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=False)),
                ('description', tinymce.models.HTMLField()),
                ('url', models.URLField(blank=True)),
                ('featured_image', models.ImageField(upload_to='project/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=200, unique=True)),
                ('src', models.ImageField(upload_to='project/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_image', to='Projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_collection', to='Projects.Collection')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_project', to='Projects.Project')),
            ],
        ),
    ]
