# Generated by Django 3.0.5 on 2020-04-30 05:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='handle',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
