# Generated by Django 3.0.5 on 2020-04-30 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20200430_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_project', to='Projects.Collection'),
        ),
        migrations.AlterField(
            model_name='projectcollection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_collection', to='Projects.Project'),
        ),
    ]
