# Generated by Django 3.0.5 on 2020-05-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20200430_0634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='paragraph',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
