# Generated by Django 3.0.5 on 2020-05-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_auto_20200502_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='paragraph',
            field=models.TextField(blank=True),
        ),
    ]
