# Generated by Django 3.0.5 on 2020-05-02 20:03

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0005_auto_20200502_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('handle', models.SlugField(blank=True, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='collections/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projects', models.ManyToManyField(to='Projects.Project')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
